name: Python and C++ application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
    
    - name: Compile C++ program
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        g++ -o data_processor data_processor.cpp

    - name: Run Python and C++ together
      run: |
        python read_sensor_data.py | data_processor

    - name: Run Python tests
      run: python test_sensor_data.py
