name: Python and C++ application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Lint Python code with flake8
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics

    # Set up C++ build tools
    - name: Install build tools for C++
      run: sudo apt-get install build-essential

    # Compile C++ code
    - name: Compile data_processor.cpp
      run: |
        g++ -o data_processor data_processor.cpp
        chmod +x data_processor

    # Run the Python and C++ programs in a pipe
    - name: Run Python and C++ in pipe
      run: python read_sensor_data.py | ./data_processor
